### ISSUE TITLE
Ready for an official package?

### ISSUE THREAD

**Issue by lars18th** [srchack/custom-packages#2]
Hi @srchack ,

I'm using your package (downloaded pre-compiled as .ipk) with one OpenWRT 18.06.1 x86_64 running inside a VM. And it works like a charm.

So, I suggest to create a PR for the official openwrt/packages repo.
https://github.com/openwrt/packages

The only requirement is to limit the target just to x86_64.

You agree?

**Comment by srchack** [comment]
I am pull req now. Please wait.
https://github.com/openwrt/packages/pull/8250

Backport to 18.0x is a problem.

**Comment by srchack** [comment]
It was merged, so I will close it.
Since openwrt 19.03 is also planned for release, I'm thinking do not to backport to 18.06.
