### ISSUE TITLE
Can't mount shared folders.

### ISSUE THREAD

**Issue by kuoruan** [srchack/custom-packages#3]
OS: OSX 10.15
VMware: VMware Fusion 11.1.0

```
# mount -t vmhgfs .host:/ /root/shares/
Error: cannot mount filesystem: No such device
mount: mounting .host:/ on /root/shares/ failed: No such device
```
```
# vmware-hgfsclient
OpenWrt
```
No open-vm-tools-dkms installed?

**Comment by kuoruan** [comment]
From https://kb.vmware.com/s/article/60262?lang=en_US

vmhgfs-fuse is needed but command not found in Makefile

**Comment by srchack** [comment]
Hi,
It has not install now.
Because I wanted to reduce the dependency.
I think, that can be option setting.
wait for me.

**Comment by kuoruan** [comment]
Any update?
I'am developing LuCI packages, need a way to mount folders to OpenWrt from Windows or OSX.
Is there any config to build open-vm-tools with vmhgfs-fuse?

**Comment by kuoruan** [comment]
https://github.com/openwrt/packages/pull/12355
